version: '3.8'
   services:
  postgres_db:
  image: postgres:latest
  container_name: PostgresCont 
  restart: always
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres123
  ports:
  - '5432:5432'
  volumes:
  - postgres_db:/var/lib/postgresql/data
   volumes:
  postgres_db:
  driver: local


#docker run --name postgresql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres#2024qaz -p 5432:5432 -v /opt/postgresql/data:/var/lib/postgresql/data -d postgres:13.3
